const ACTIONS = {
  CREATE_ROOM: 'CREATE_ROOM',
  JOIN: 'JOIN',
  LEAVE: 'LEAVE',
  SHARE_ROOMS: 'SHARE_ROOMS',
  ADD_PEER: 'ADD_PEER',
  REMOVE_PEER: 'REMOVE_PEER',
  RELAY_SDP: 'RELAY_SDP',
  RELAY_ICE: 'RELAY_ICE',
  ICE_CANDIDATE: 'ICE_CANDIDATE',
  SESSION_DESCRIPTION: 'SESSION_DESCRIPTION',
  SET_VOLUME: 'SET_VOLUME',
  SET_MUTE: 'SET_MUTE',
  SHARE_USERS: 'SHARE_USERS',
};
module.exports = ACTIONS;
